import React from 'react'


export const metadata = {
  title: "Eghost Backend",
  description: "Generated by next app",
};
const RootLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}

export default RootLayout